"""
rtf_core/db.py
--------------
Database engine and session management.
Creates all tables automatically on first run.
Uses the existing PostgreSQL 'redteam' database.
"""

import datetime
from contextlib import contextmanager
from sqlalchemy import (
    create_engine, Column, Integer, String, Text,
    Float, DateTime, JSON, ForeignKey, Boolean
)
from sqlalchemy.orm import declarative_base, relationship, sessionmaker
from rtf_core import settings

# ─── Engine ──────────────────────────────────────────────────────────────────
engine = create_engine(
    settings.DATABASE_URL,
    pool_size=5,
    max_overflow=10,
    pool_pre_ping=True,   # drop stale connections gracefully
)

Base = declarative_base()
SessionLocal = sessionmaker(bind=engine, autocommit=False, autoflush=False)


# ─── ORM Models ──────────────────────────────────────────────────────────────

class SessionDB(Base):
    """One red-team session (scoped run)."""
    __tablename__ = "rtf_sessions"

    session_id       = Column(String, primary_key=True)
    name             = Column(String, default="Unnamed Session")
    scope_text       = Column(Text)
    webhook_url      = Column(Text)
    model_name       = Column(String, nullable=True)
    start_time       = Column(DateTime, default=datetime.datetime.utcnow)
    end_time         = Column(DateTime, nullable=True)
    total_probes     = Column(Integer, default=0)
    vulnerabilities  = Column(Integer, default=0)
    risk_score       = Column(Float, default=0.0)
    status           = Column(String, default="active")   # active | completed | aborted
    memory_snapshot  = Column(JSON, nullable=True)        # final ProbeMemory dict


class ProbeDB(Base):
    """Individual probe dispatch record."""
    __tablename__ = "rtf_probes"

    id                  = Column(Integer, primary_key=True, autoincrement=True)
    session_id          = Column(String, ForeignKey("rtf_sessions.session_id"))
    probe_text          = Column(Text)
    victim_response     = Column(Text, nullable=True)
    vulnerability_found = Column(Boolean, default=False)
    weak_area           = Column(String, nullable=True)
    key_insight         = Column(Text, nullable=True)
    severity            = Column(Integer, default=1)      # 1-5
    strategy_tag        = Column(String, nullable=True)
    status              = Column(String, default="pending")  # pending | judged | failed
    created_at          = Column(DateTime, default=datetime.datetime.utcnow)


class MutatedPromptDB(Base):
    """Mutated prompts generated by the Mutation Engine."""
    __tablename__ = "rtf_mutations"

    id               = Column(Integer, primary_key=True, autoincrement=True)
    session_id       = Column(String, ForeignKey("rtf_sessions.session_id"), nullable=True)
    parent_probe_id  = Column(Integer, ForeignKey("rtf_probes.id"), nullable=True)
    prompt_text      = Column(Text)
    persona_used     = Column(String, nullable=True)
    weak_areas       = Column(JSON, nullable=True)       # list of targeted weak areas
    created_at       = Column(DateTime, default=datetime.datetime.utcnow)
    # Execution results (filled after Execute Attacks)
    victim_response  = Column(Text, nullable=True)
    vulnerability_found = Column(Boolean, nullable=True)
    severity         = Column(Integer, nullable=True)
    executed_at      = Column(DateTime, nullable=True)


class ToolAbuseProbeDB(Base):
    """Tool abuse specific probes and findings."""
    __tablename__ = "rtf_tool_abuse_probes"

    id                  = Column(Integer, primary_key=True, autoincrement=True)
    session_id          = Column(String, ForeignKey("rtf_sessions.session_id"))
    turn                = Column(Integer, default=0)
    vector              = Column(String, nullable=True)
    probe_text          = Column(Text)
    victim_response     = Column(Text, nullable=True)
    vulnerability_found = Column(Boolean, default=False)
    severity            = Column(Float, default=0.0)      # 0.0 - 1.0 (will map to 1-5 for pdf)
    attack_category     = Column(String, nullable=True)
    primary_tool_type   = Column(String, nullable=True)
    key_finding         = Column(Text, nullable=True)
    evidence            = Column(Text, nullable=True)
    tools_involved      = Column(JSON, nullable=True)
    tool_calls          = Column(JSON, nullable=True)
    was_refused         = Column(Boolean, default=False)
    created_at          = Column(DateTime, default=datetime.datetime.utcnow)


class GenomeDB(Base):
    """Genome gene pool for the mutation engine (existing table, extended)."""
    __tablename__ = "genomes"
    __table_args__ = {"extend_existing": True}

    id               = Column(Integer, primary_key=True, autoincrement=True)
    genome_id        = Column(String, unique=True, index=True)
    prompt_text      = Column(Text)
    technique        = Column(String)
    persona          = Column(String, default="none")
    framing          = Column(String)
    encoding         = Column(String)
    nesting_depth    = Column(Integer)
    complexity_score = Column(Float)
    features_json    = Column(JSON, nullable=True)
    parent_id        = Column(Integer, ForeignKey("genomes.id"), nullable=True)
    severity_score   = Column(Float, default=0.0)
    persona_tag      = Column(String, nullable=True)


# ─── Helpers ─────────────────────────────────────────────────────────────────

def init_db():
    """Create all RTF tables if they don't exist. Safe to call repeatedly."""
    Base.metadata.create_all(bind=engine, checkfirst=True)


@contextmanager
def get_session():
    """Context manager yielding a transactional DB session."""
    session = SessionLocal()
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()


def test_db_connection() -> tuple[bool, str]:
    """Ping the database. Returns (ok, message)."""
    try:
        from sqlalchemy import text
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return True, "Database connection successful"
    except Exception as e:
        return False, f"DB Error: {e}"
